# platform :ios, ’10.0’
# Uncomment this line if you're using Swift
#use_frameworks!

target 'Socket Connection' do
use_frameworks!
pod 'SwiftCharts', '~> 0.6'
end

target 'Socket ConnectionTests' do

end

target 'Socket ConnectionUITests' do

end

